//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueHandymans.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandyMansRequest
    {
        public int HandyMansRequest1 { get; set; }
        public string RequesterName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> HandyMansServiceID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual District District { get; set; }
        public virtual HandyMansService HandyMansService { get; set; }
        public virtual Place Place { get; set; }
    }
}
