//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueHandymans.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RescueNeedsEntities : DbContext
    {
        public RescueNeedsEntities()
            : base("name=RescueNeedsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CampInCharge> CampInCharges { get; set; }
        public virtual DbSet<CampRequirement> CampRequirements { get; set; }
        public virtual DbSet<Camp> Camps { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<HandyMan> HandyMans { get; set; }
        public virtual DbSet<HandyMansRequest> HandyMansRequests { get; set; }
        public virtual DbSet<HandyMansService> HandyMansServices { get; set; }
    }
}
